
version: 2
jobs:
  build:
    docker:
      - image: lindybritsimmerse/my-first-repo:myimage
    steps:
      - checkout
      - run:
          name: "Run FE Tests"
          command: pushd circleci && yarn run test && popd
workflows:
  version: 2
  build_test:
    jobs:
      - build


        
