# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - run:
          name: "Installation"
          command: pushd circleci && yarn install && popd
      - run:
          name: "Linting"
          command: npm run lint
      - run:
          name: "Testing"
          command: npm run test
      - run:
          name: "End to End Test"
          command: npm run e2e
workflows:
  version: 2
  testing:
    jobs:
      - test
