
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Run Docker"
          command: pushd scripts && ./run_docker.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
