
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - run:
          name: "Generate Test File"
          command: echo "Boom test!" > test.txt
#  test:
#    docker:
#      - image: circleci/node:10.16-browsers
#    steps:
#      - checkout
workflows:
  version: 2
  build_test:
    jobs:
      - build
#      - test:
#          requires:
#            - build
