# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  angular_testing:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - run:
          name: "Installation"
          command: pushd circleci && yarn install
#      - run: echo "Hello world! :)"
#      - run: mkdir -p my_workspaces
#      - run: echo "Trying out workspaces" > my_workspaces/echo-output
#      - persist_to_workspace:
#          root: my_workspaces
#          paths:
#            - echo-output
  coverage_analysis:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "I am awake!"
#      - attach_workspace:
#          at: my_workspaces
#      - run: echo "Boom!"
workflows:
  version: 2
  testing:
    jobs:
      - angular_testing
      - coverage_analysis:
          requires:
            - angular_testing
