
version: 2
jobs:
  build:
    docker:
      - image: lindybritsimmerse/my-first-repo:myimage
    steps:
      - checkout
      - run:
          name: "FE Tests"
          command: yarn run test
workflows:
  version: 2
  build_test:
    jobs:
      - build
