
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /cache/app.tar
      - run:
          name: "Generate Test File"
          command: echo "Boom test!" > test.txt
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - /caches/app.tar
#  test:
#    steps:
workflows:
  version: 2
  build_test:
    jobs:
      - build
#      - test:
#          requires:
#            - build
