# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - run:
          name: "Installation"
          command: pushd circleci && yarn install && popd
      - run:
          name: "Linting"
          command: pushd circleci && yarn run lint && popd
      - run:
          name: "Testing"
          command: pushd circleci && npm run test && popd
#      - run:
#          name: Save test results
#          command: |
#            mkdir -p ~/cucumber
#            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
#          when: always
      - store_test_results:
          path: ./circleci/cucumber
workflows:
  version: 2
  testing:
    jobs:
      - test
