# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: "Installation"
          command: pushd circleci && yarn install && popd
  test:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
